---
title: "Readme"
author: "Herbert Santos e Marilia Santiago"
date: "03/03/2021"
output:
  github_document:
    fig_width: 9
    fig_height: 5
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Diario de Classe

<h3 align="left" id ='Sobre'>Descrição</h3>
<p align="left">O objetivo dese projeto é permitir o registro das vivências diárias de uma sala de aula em um ambiente digital</p>

Conteúdo
=================
<!--ts-->
   * [Sobre](#Sobre)
   * [Andamento](#andamento)
   * [Funções](#funcoes)
      * [Registro de presença](#presenca)
      * [Percentual de faltas](#faltas)
      * [Registro de notas](#notas)
      * [Calculo da média](#media)
      * [Parecer do aluno](#parecer)
   * [Ferramentas e pacotes](#tecnologias)
<!--te-->

<h2 id='andamento'>Andamento</h2>
<h4 align="left"> 
	🚧  Em construção...  🚧
</h4>

<h1 id='funcoes'>Funções: </h1>

<h3 id='presenca'>Registro de presença </h3>
<p align="left">Aqui o(a) professor(a) irá registrar a presença do aluno diariamente.</p>

<h3 id='faltas'>Percentual de faltas</h3>
<p align="left">O sistema irá calcular o percentual de faltas a partir da quantidade de dias letivos e a quantidade de presenças do aluno.</p>

<h3 id='notas'>Registro de notas</h3>
<p align="left">Essa opção permite ao professor(a) registrar as notas do aluno para as atividades realizadas.</p>

<h3 id='media'>Cálculo da média</h3>
<p align="left">O sistema irá calcular a média de acordo com a quantidade de notas registtradas para o aluno.</p>

<h2 id='parecer'>Parecer do aluno</h2>
<p align="left">Nesse tópico o(a) professor(a) irá descrever a como anda o desenvolvimento do aluno.</p>

<h2 id='tecnologias'>🛠 Ferramentas e Pacotes</h2>

As seguintes ferramentas foram usadas na construção do projeto:

- [Linguagem R](https://www.r-project.org/)
- [RStudio](https://rstudio.com/)
- [Git](https://git-scm.com/)
- [Pacotes a definir]()

MIT License

Copyright (c) <2021> <Herbert Santos e Marília Santiago>

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.


